"""PR Summary Generator feature."""

import logging

from llm.client import LLMClient
from llm.prompts import PR_SUMMARY_SYSTEM, PR_SUMMARY_USER

logger = logging.getLogger("oss-maintainer-bot.summarize_prs")

LANGUAGE_NAMES = {
    "en": "English",
    "zh": "Chinese (Simplified)",
    "ja": "Japanese",
    "es": "Spanish",
    "fr": "French",
}


class SummarizePRsFeature:
    """Generates AI-powered summaries for pull requests."""

    def __init__(self, config: dict, gh_client):
        self.config = config
        self.gh = gh_client
        self.llm = LLMClient(
            api_key=config["openai_api_key"],
            model=config["model"],
        )
        self.language = config.get("language", "en")

    def run(self, pr: dict) -> bool:
        """
        Generate and post a summary for the given PR payload.
        Returns True if summary was successfully posted.
        """
        number = pr.get("number", 0)
        title = pr.get("title", "").strip()

        logger.info("Generating summary for PR #%d: %s", number, title)

        # Fetch full PR object for diff access
        try:
            pr_obj = self.gh.get_pr(number)
        except Exception as exc:
            logger.error("Failed to fetch PR #%d: %s", number, exc)
            return False

        diff = self.gh.get_pr_diff(pr_obj)
        commits = self._get_commit_messages(pr_obj)
        lang_name = LANGUAGE_NAMES.get(self.language, "English")

        system = PR_SUMMARY_SYSTEM.format(language=lang_name)
        user = PR_SUMMARY_USER.format(
            title=title,
            commits="\n".join(f"- {c}" for c in commits[:20]),
            diff=diff,
        )

        summary = self.llm.complete(
            system_prompt=system,
            user_prompt=user,
            temperature=0.4,
            max_tokens=600,
        )

        if not summary:
            logger.warning("LLM returned empty summary for PR #%d", number)
            return False

        comment = (
            "## 🤖 AI-Generated PR Summary\n\n"
            f"{summary}\n\n"
            "---\n"
            "*Generated by [OSS Maintainer Bot](https://github.com/seedawn2013/oss-maintainer-bot)*"
        )

        self.gh.post_pr_comment(number, comment)
        logger.info("Posted PR summary for #%d", number)
        return True

    def _get_commit_messages(self, pr_obj) -> list[str]:
        """Extract commit messages from a PR object."""
        try:
            return [c.commit.message.split("\n")[0] for c in pr_obj.get_commits()]
        except Exception as exc:
            logger.warning("Could not fetch commits for PR: %s", exc)
            return []
